model:
  base_learning_rate: 1.0e-05
  target: zero123plus_material.model.MVDiffusion
  params:
    drop_cond_prob: 0.1

    stable_diffusion_config:
      pretrained_model_name_or_path: sudo-ai/zero123plus-v1.2
      custom_pipeline: ./zero123plus_material
    
    # white_back_unet_path: /mnt/petrelfs/wangzhenwei/projects/ThemeStationPro/InstantMesh/ckpts/diffusion_pytorch_model.bin
    # white_back_unet_path: /mnt/petrelfs/wangzhenwei/projects/ThemeStationPro/InstantGTA3/workspace/z123p_no_ref/zero123plus-finetune-instantmesh_render_lr1e-6-v3_hybrid0.8_noRS_noFL/unet_0002000/diffusion_pytorch_model.safetensors
    white_back_unet_path: ./pretrained/phidias_whitebg0123pp.safetensors

    train_controlnet: true


data:
  target: core.objaverse_zero123plus_material.DataModuleFromConfig
  params:
    batch_size: 6 #6
    num_workers: 8 #8
    train:
      target: core.objaverse_zero123plus_material.ObjaverseData
      params:
        root_dir: ["/mnt/hwfile/3dobject_aigc/wangzhenwei/datasets/render-v6",]
        meta_fname: "/mnt/petrelfs/wangzhenwei/projects/ThemeStationPro/InstantGTA3/data_train/Objaverse/rendered/render-v5-20240408/train.json"
        cond_map: ['rgb']
        ref_maps: ['rgb']
        target_map: 'normals'
        # downsample_size: null
        # upsample_size: 320
        # augmentation prob for grid distortion
        # prob_grid_distortion: null
        # random_resize_ref: null
    validation:
      target: core.objaverse_zero123plus_material.ObjaverseData
      params:
        root_dir: ["/mnt/hwfile/3dobject_aigc/wangzhenwei/datasets/render-v6",]
        meta_fname: "/mnt/petrelfs/wangzhenwei/projects/ThemeStationPro/InstantGTA3/data_train/Objaverse/rendered/render-v5-20240408/val.json"
        cond_map: ['rgb']
        ref_maps: ['rgb']
        target_map: 'normals'
        # downsample_size: null
        # upsample_size: 320
        # prob_grid_distortion: null
        # random_resize_ref: null




lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 200
      save_top_k: 1
      save_last: true
      enable_version_counter: false
  callbacks: {}

  trainer:
    benchmark: true
    max_steps: 10000
    gradient_clip_val: 1.0
    val_check_interval: 2000
    num_sanity_val_steps: -1
    accumulate_grad_batches: 1
    check_val_every_n_epoch: null   # if not set this, validation does not run
