model:
  base_learning_rate: 1.0e-05
  target: zero123plus_material.model.MVDiffusion
  params:
    drop_cond_prob: 0.1

    stable_diffusion_config:
      pretrained_model_name_or_path: sudo-ai/zero123plus-v1.2
      custom_pipeline: ./zero123plus_material
    
    white_back_unet_path:  ./pretrained/phidias_whitebg0123pp.safetensors
    vae_path:

    train_controlnet: false
    one_step: true # one_step diffusion
    front_guided: true
    image_loss: true
    render_loss: true
    finetune_vae_decoder: true
    domains: ["rgb", "albedo", "normal", "depth", "roughness", "metallic"]
    weights_domains: [1.0, 1.0, 0.5, 0.5, 3.0, 3.0] # weight for each domain "rgb", "albedo", "normal", "depth", "roughness", "metallic"
    weight_lpips: 1.0
    weight_global_mse: 10
    weight_render_loss: 10



data:
  target: core.objaverse_zero123plus_material.DataModuleFromConfig
  params:
    batch_size: 6 #6
    num_workers: 8 #8
    train:
      target: core.objaverse_zero123plus_material.ObjaverseData
      params:
        root_dir: ["/n/holyscratch01/pfister_lab/zwwang/dataset/mat3d/render-v8/render-v8",]
        meta_fname: "./data_train/lvis18k_filtered/render-v8-18k_rm_unaligned_train.json"
        ref_maps: null
        cond_map: ['rgb']
        target_map: "tailed_multi_domain" # "tailed multi-domain" |'same_as_cond'
        front_guided: true
        bg_color: 1.0
        rand_view: true
        # downsample_size: null
        # upsample_size: 320
        # augmentation prob for grid distortion
        # prob_grid_distortion: null
        # random_resize_ref: null
    validation:
      target: core.objaverse_zero123plus_material.ObjaverseData
      params:
        root_dir: ["/n/holyscratch01/pfister_lab/zwwang/dataset/mat3d/render-v8/render-v8",]
        meta_fname: "./data_train/lvis18k_filtered/render-v8-18k_rm_unaligned_val.json"
        ref_maps: null
        cond_map: ['rgb']
        target_map: "tailed_multi_domain" # 'same_as_cond'
        front_guided: true
        bg_color: 1.0
        rand_view: false
        # downsample_size: null
        # upsample_size: 320
        # prob_grid_distortion: null
        # random_resize_ref: null




lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 250
      save_top_k: 1
      save_last: true
      enable_version_counter: false
  callbacks: {}

  trainer:
    benchmark: true
    max_steps: 10000
    gradient_clip_val: 1.0
    val_check_interval: 1000
    num_sanity_val_steps: -1
    accumulate_grad_batches: 1
    check_val_every_n_epoch: null   # if not set this, validation does not run
